aug_list:
- 'hsv_random_brightness'
- 'hsv_random_contrast'
- 'hsv_gamma_correction'
- 'gaussian_noise'
- 'flip'
task: 'homogenity_cls'
root_dir: '/home/hocheol/inskin_ai/no_track/datasets/age_data/v0.3/v0.3_data'
meta_file: '/home/hocheol/inskin_ai/trashlab/skin_homogenity/homogenity_label_paths.json'
save_dir: '/home/hocheol/inskin_ai/no_track/save_models/homogenity/v0.1.0'
batch_size: 64
epochs: 70
learning_rate: 0.00005
kernel_regularizer: 0.01
model_size: 'S'
input_shape: [384, 384, 3]
one_hot: true
comment: 'homogenity 모델 학습 시작'
loss: 'categorical_crossentropy'